### ISSUE TITLE
Nested properties don't highlight correctly

### ISSUE THREAD

**Issue by yb53** [braver/SublimeSass#16]
Hi, 

Firsdt of all, thank you for your hard work. Here are just 2 trivial regressions from the previous version, the first one about property nesting and the second about function parameters.

![nesting1](https://user-images.githubusercontent.com/41319134/47760188-4e635b80-dcf6-11e8-948c-95b1005f1ce8.png)
 
Except for "size", all other nested parameters (weight, style, radius, appearance, etc) are not recognized and end up constituing a funny color pattern.

![functions1](https://user-images.githubusercontent.com/41319134/47760203-63d88580-dcf6-11e8-9b00-55abdce8e9a5.png)

As for the function parameter, the "$foo" is not identified and not highlighted.

Of course it is the same for this kind of declarations:
=background-size($property)
　-webkit-background-size: $property
　-moz-background-size:    $property
　  background-size:         $property

Thank you again for your work, and if you ever have a sparetime with nothing to do, then perhaps~

**Comment by raedlime** [comment]
I have a similar issue with mixins and comments within the sass-highlighting.
Some mixins are highlighted correctly, some are not.

Comments are not even possible with the shortcut inside Sublime Text 3.

Am I missing sth. ore ist that a real issue?

For example:

![bildschirmfoto 2018-10-31 um 11 37 49](https://user-images.githubusercontent.com/17073009/47782853-7e642c00-dd01-11e8-9304-9748ce781a38.png)

![bildschirmfoto 2018-10-31 um 11 36 03](https://user-images.githubusercontent.com/17073009/47782865-8623d080-dd01-11e8-87dc-d688c812c958.png)

![bildschirmfoto 2018-10-31 um 11 44 41](https://user-images.githubusercontent.com/17073009/47783197-6214bf00-dd02-11e8-810f-73970a739b99.png)

**Comment by braver** [comment]
I think I'm missing some key syntax features here for Sass specifically, like the `=<mixin>` and `+<include mixin>`: http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html#Mixin_Directives

That should be an easy fix, I'll let you know what I come up with

**Comment by braver** [comment]
@raedlime 2.0.4 should become available soon with fixes:

- commenting using the key binding should work again
- `+` and `=` syntax for mixins should be supported now. I probably need to add more test cases to cover everything, but should be a lot better than before :)

**Comment by raedlime** [comment]
Okay, nice. Waiting for the upgrade then.

**Comment by raedlime** [comment]
Got the upgrade now. Comments are possible now, but the thing with the mixins highlighting still doesn't work properly.

Example v.1.:
![bildschirmfoto 2018-10-31 um 17 07 32](https://user-images.githubusercontent.com/17073009/47801912-79b66c80-dd2f-11e8-9e5d-5693f1d2cf0c.png)

Example: v.2.:
![bildschirmfoto 2018-10-31 um 17 08 14](https://user-images.githubusercontent.com/17073009/47801957-9357b400-dd2f-11e8-9590-68bf980ca8ca.png)

**Comment by braver** [comment]
@raedlime this should be fixed in 2.0.5 already (although the `@content` keyword is missing):
<img width="212" alt="screen shot 2018-10-31 at 17 28 44" src="https://user-images.githubusercontent.com/2543659/47803309-753f8300-dd32-11e8-9833-d283bfff76fc.png">

**Comment by raedlime** [comment]
mh, okay. Idk what's wrong with my sass then. But it looks like, the @content keyword breaks every thing following.

**Comment by dr-dimitru** [comment]
@braver 

> Anyway, hope you enjoy the improvements the new syntax brings. These and other improvements are sure to follow.

Can't enjoy it, all broken in deeply nested trees 😞

But, I love your fork of the lib, and don't wanna go to original package.
Any options? What last stable version?

**Comment by braver** [comment]
@dr-dimitru can you give me a test file so I can see what’s wrong?

**Comment by dr-dimitru** [comment]
@braver sure, actually I found exact line was causing it, right after multiple `:not(/*...*/)`:
```sass
input:not([type="radio"]):not([type="checkbox"]):not([type="range"]):not([type="image"]), select, textarea
  display: block
  transition-property: background-color, border-color
  transition-duration: 256ms
  transition-timing-function: ease
  background-color: $white
  border: 1px solid lighten($black, 75%)
  padding: 6px 10px
  border-radius: 2px
  width: 100%
  min-width: 80px
  font-weight: 400
```

And commenting with double-slash `//`

You should be able to reproduce on your end, details:
 - MacOS X 10.13.6
 - Sublime 3.1.1
 - node-sass@4.9.4
 - (_this package_) sublime sass at the latest version

**Comment by michaelblyons** [comment]
It looks like a single `:not([attr])` is enough to trigger the problem. The `meta.function-call meta.group` stacks never pop.

``` sass
:not([attr])
  display: block
```

**Comment by braver** [comment]
Thanks guys, that should be fixable.

**Comment by braver** [comment]
Fixed in 89dab3a

**Comment by michaelblyons** [comment]
`89dab3a` fixed OP's case and `:not(.class)`. Is `:not(tag)` valid Sass? Because that still doesn't pop.

(Maintenance of a popular package seems to be a huge chore. 😉)

**Comment by braver** [comment]
> Maintenance of a popular package seems to be a huge chore

Yeah, some maintainers tend to go with *not* actually doing the maintenance 😉 This is all good though, lot's of use cases I don't come across myself a lot. Just some things to get right and if I set it up correctly I think it'll be peanuts later.

**Comment by dr-dimitru** [comment]
@michaelblyons @braver `:not()` can be used with any selector class, id, element name

**Comment by braver** [comment]
@dr-dimitru @michaelblyons thanks guys, caught those as well now.

**Comment by dr-dimitru** [comment]
@braver thanks for quick update, testing now.
Everything seems to be good, but still feels like something off, like color schema changed, or ... idk...

I'll report if something will popup later.

**Comment by raedlime** [comment]
Most of the highlighting works pretty awesome. Thanks for the work on the issues found last week (y)
But, I found some little issues this morning. I hope, I don't annoy you... but I think, we all want this to work properly :-) 

Here are the little issues I'm talking about:

![bildschirmfoto 2018-11-05 um 11 52 07](https://user-images.githubusercontent.com/17073009/47994123-ae407480-e0f1-11e8-92ea-522401208b53.png)
![bildschirmfoto 2018-11-05 um 11 53 23](https://user-images.githubusercontent.com/17073009/47994130-b13b6500-e0f1-11e8-9db7-2221583e4c3c.png)

When I use "background-image" on it's own, it works perfectly:

![bildschirmfoto 2018-11-05 um 11 52 22](https://user-images.githubusercontent.com/17073009/47994162-d039f700-e0f1-11e8-9598-86c908ba1440.png)

**Comment by braver** [comment]
Should be fixed in 2.2!
